import type { NextPage } from 'next'
import Head from 'next/head'
import Link from "next/link"
import { Grid, Card, CardContent, Typography } from '@mui/material'
import Header from "../components/Header";
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Header title="Titles" />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Grid container spacing={2}>
          <Grid item xs={12} md={2}>
            <Link href="/movies">
              <Card sx={{ maxWidth: 345, cursor: "pointer" }}>
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                      <h1>Movies</h1>
                  </Typography>
                </CardContent>
              </Card>
            </Link>
          </Grid>
          <Grid item xs={12} md={2}>
            <Link href="/series">
              <Card sx={{ maxWidth: 345, cursor: "pointer" }}>
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                      <h1>Series</h1>
                  </Typography>
                </CardContent>
              </Card>
            </Link>
          </Grid>
        </Grid>
      </div>
    </>
  )
}

export default Home
